/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EMIPlansArray } from "./emiplansarray";
import { Expose, Type } from "class-transformer";

export class CardlessEMIEntity extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: EMIPlansArray })
    @Expose({ name: "emi_plans" })
    @Type(() => EMIPlansArray)
    emiPlans?: EMIPlansArray[];

    @SpeakeasyMetadata()
    @Expose({ name: "payment_method" })
    paymentMethod?: string;
}
