/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CustomerDetailsCardlessEMI } from "./customerdetailscardlessemi";
import { Expose, Type } from "class-transformer";

export class CardlessEMIQueries extends SpeakeasyBase {
    /**
     * Amount of the order. OrderId of the order. Either of `order_id` or `amount` is mandatory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    /**
     * Details of the customer for whom eligibility is being checked.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_details" })
    @Type(() => CustomerDetailsCardlessEMI)
    customerDetails?: CustomerDetailsCardlessEMI;

    /**
     * OrderId of the order. Either of `order_id` or `amount` is mandatory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId?: string;
}
