/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CardlessEMI } from "./cardlessemi";
import { Expose, Type } from "class-transformer";

export class CardlessEMIPaymentMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cardless_emi" })
    @Type(() => CardlessEMI)
    cardlessEmi: CardlessEMI;
}
