/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CardEMI } from "./cardemi";
import { Expose, Type } from "class-transformer";

export class CardEMIPaymentMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "emi" })
    @Type(() => CardEMI)
    emi?: CardEMI;
}
