/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * One of ["Kotak", "ICICI", "RBL", "BOB", "Standard Chartered"]. Card bank name, required for EMI payments. This is the bank user has selected for EMI
 */
export enum CardCardBankName {
    Kotak = "Kotak",
    Icici = "ICICI",
    Rbl = "RBL",
    Bob = "BOB",
    StandardChartered = "Standard Chartered",
}

/**
 * The channel for card payments can be "link" or "post". Post is used for seamless OTP payments where merchant captures OTP on their own page.
 */
export enum CardChannel {
    Link = "link",
    Post = "post",
}

export class Card extends SpeakeasyBase {
    /**
     * Card alias as returned by Cashfree Vault API.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_alias" })
    cardAlias?: string;

    /**
     * One of ["Kotak", "ICICI", "RBL", "BOB", "Standard Chartered"]. Card bank name, required for EMI payments. This is the bank user has selected for EMI
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_bank_name" })
    cardBankName?: CardCardBankName;

    /**
     * CVV mentioned on the card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_cvv" })
    cardCvv?: string;

    /**
     * last 4 digits of original card number. Required only for tokenized card transactions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_display" })
    cardDisplay?: string;

    /**
     * Card expiry month for plain card transactions. Token expiry month for tokenized card transactions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_expiry_mm" })
    cardExpiryMm?: string;

    /**
     * Card expiry year for plain card transactions. Token expiry year for tokenized card transactions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_expiry_yy" })
    cardExpiryYy?: string;

    /**
     * Customer name mentioned on the card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_holder_name" })
    cardHolderName?: string;

    /**
     * Customer card number for plain card transactions. Token pan number for tokenized card transactions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_number" })
    cardNumber?: string;

    /**
     * The channel for card payments can be "link" or "post". Post is used for seamless OTP payments where merchant captures OTP on their own page.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "channel" })
    channel?: CardChannel;

    /**
     * cryptogram received from card network. Required only for tokenized card transactions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cryptogram" })
    cryptogram?: string;

    /**
     * EMI tenure selected by the user
     */
    @SpeakeasyMetadata()
    @Expose({ name: "emi_tenure" })
    emiTenure?: number;

    /**
     * instrument id of saved card. Required only to make payment using saved instrument.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instrument_id" })
    instrumentId?: string;

    /**
     * TRID issued by card networks. Required only for tokenized card transactions.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "token_requestor_id" })
    tokenRequestorId?: string;
}
