/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Card bank name, required for EMI payments. This is the bank user has selected for EMI. One of ["hdfc, "kotak", "icici", "rbl", "bob", "standard chartered", "axis", "au", "yes", "sbi", "fed", "hsbc", "citi", "amex"]
 */
export enum CardEMICardBankName {
    Hdfc = "hdfc",
    Kotak = "kotak",
    Icici = "icici",
    Rbl = "rbl",
    Bob = "bob",
    StandardChartered = "standard chartered",
    Axis = "axis",
    Au = "au",
    Yes = "yes",
    Sbi = "sbi",
    Fed = "fed",
    Hsbc = "hsbc",
    Citi = "citi",
    Amex = "amex",
}

export class CardEMI extends SpeakeasyBase {
    /**
     * Card alias as returned by Cashfree Vault API
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_alias" })
    cardAlias?: string;

    /**
     * Card bank name, required for EMI payments. This is the bank user has selected for EMI. One of ["hdfc, "kotak", "icici", "rbl", "bob", "standard chartered", "axis", "au", "yes", "sbi", "fed", "hsbc", "citi", "amex"]
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_bank_name" })
    cardBankName?: CardEMICardBankName;

    /**
     * CVV mentioned on the card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_cvv" })
    cardCvv?: string;

    /**
     * Card expiry month.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_expiry_mm" })
    cardExpiryMm?: string;

    /**
     * Card expiry year.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_expiry_yy" })
    cardExpiryYy?: string;

    /**
     * Customer name mentioned on the card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_holder_name" })
    cardHolderName?: string;

    /**
     * Customer card number.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_number" })
    cardNumber?: string;

    /**
     * The channel for card payments will always be "link"
     */
    @SpeakeasyMetadata()
    @Expose({ name: "channel" })
    channel?: string;

    /**
     * EMI tenure selected by the user
     */
    @SpeakeasyMetadata()
    @Expose({ name: "emi_tenure" })
    emiTenure?: number;
}
