/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CardOffer extends SpeakeasyBase {
    /**
     * Bank Name of Card.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "bank_name" })
    bankName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "scheme_name" })
    schemeName: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: string[];
}
