/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Type of discount
 */
export enum CashbackType {
    Flat = "flat",
    Percentage = "percentage",
}

export class CashbackDetails extends SpeakeasyBase {
    /**
     * Type of discount
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cashback_type" })
    cashbackType?: CashbackType;

    /**
     * Value of Discount.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cashback_value" })
    cashbackValue?: string;

    /**
     * Maximum Value of Cashback allowed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "max_cashback_amount" })
    maxCashbackAmount: string;
}
