/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OfferDetails } from "./offerdetails";
import { OfferMeta } from "./offermeta";
import { OfferTnc } from "./offertnc";
import { OfferValidations } from "./offervalidations";
import { Expose, Type } from "class-transformer";

export class CreateOfferBackendRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "offer_details" })
    @Type(() => OfferDetails)
    offerDetails: OfferDetails;

    @SpeakeasyMetadata()
    @Expose({ name: "offer_meta" })
    @Type(() => OfferMeta)
    offerMeta: OfferMeta;

    @SpeakeasyMetadata()
    @Expose({ name: "offer_tnc" })
    @Type(() => OfferTnc)
    offerTnc: OfferTnc;

    @SpeakeasyMetadata()
    @Expose({ name: "offer_validations" })
    @Type(() => OfferValidations)
    offerValidations: OfferValidations;
}
