/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Details of the customer for whom eligibility is being checked.
 */
export class CustomerDetailsCardlessEMI extends SpeakeasyBase {
    /**
     * Phone Number of the customer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_phone" })
    customerPhone: string;
}
