/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CardlessEMIEntity } from "./cardlessemientity";
import { Expose, Type } from "class-transformer";

export class EligibleCardlessEMIEntity extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "eligibility" })
    eligibility?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_details" })
    @Type(() => CardlessEMIEntity)
    entityDetails?: CardlessEMIEntity;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_type" })
    entityType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_value" })
    entityValue?: string;
}
