/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OfferEntity } from "./offerentity";
import { Expose, Type } from "class-transformer";

export class EligibleOffersEntity extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "eligibility" })
    eligibility?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_details" })
    @Type(() => OfferEntity)
    entityDetails?: OfferEntity;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_type" })
    entityType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_value" })
    entityValue?: string;
}
