/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PaylaterEntity } from "./paylaterentity";
import { Expose, Type } from "class-transformer";

export class EligiblePaylater extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "eligibility" })
    eligibility?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_details" })
    @Type(() => PaylaterEntity)
    entityDetails?: PaylaterEntity;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_type" })
    entityType?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "entity_value" })
    entityValue?: string;
}
