/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
 */
export class FetchSettlementReconRequestFilters extends SpeakeasyBase {
    /**
     * List of settlement IDs for which you want the settlement reconciliation details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cf_settlement_ids" })
    cfSettlementIds?: number[];

    /**
     * Specify the end date till when you want the settlement reconciliation details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "end_date" })
    endDate?: string;

    /**
     * List of settlement UTRs for which you want the settlement reconciliation details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "settlement_utrs" })
    settlementUtrs?: string[];

    /**
     * Specify the start date from when you want the settlement reconciliation details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "start_date" })
    startDate?: string;
}

/**
 * To fetch the next set of settlements, pass the cursor received in the response to the next API call.
 *
 * @remarks
 *  To receive the data for the first time, pass the cursor as null.
 *  Limit would be number of settlements that you want to receive.
 */
export class FetchSettlementReconRequestPagination extends SpeakeasyBase {
    /**
     * Specifies from where the next set of settlement details should be fetched.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cursor" })
    cursor?: string;

    /**
     * The number of settlements you want to fetch. Maximum limit is 1000, default value is 10.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "limit" })
    limit: number;
}

export class FetchSettlementReconRequest extends SpeakeasyBase {
    /**
     * Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "filters" })
    @Type(() => FetchSettlementReconRequestFilters)
    filters: FetchSettlementReconRequestFilters;

    /**
     * To fetch the next set of settlements, pass the cursor received in the response to the next API call.
     *
     * @remarks
     *  To receive the data for the first time, pass the cursor as null.
     *  Limit would be number of settlements that you want to receive.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "pagination" })
    @Type(() => FetchSettlementReconRequestPagination)
    pagination: FetchSettlementReconRequestPagination;
}
