/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class FetchSettlementData extends SpeakeasyBase {
    /**
     * Amount that is adjusted from the settlement amount.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "adjustment" })
    adjustment?: number;

    /**
     * Net amount that is settled after deducting the settlement charges and tax. (Settlement charges and tax is applicable for instant and on demand settlements.)
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount_settled" })
    amountSettled?: number;

    /**
     * Unique ID to identify the settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cf_settlement_id" })
    cfSettlementId?: number;

    /**
     * Event type is SETTLEMENT.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "event_type" })
    eventType?: string;

    /**
     * Amount captured.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_amount" })
    paymentAmount?: number;

    /**
     * The start time of time range of settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_from" })
    paymentFrom?: string;

    /**
     * The end time of time range of settlement
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_till" })
    paymentTill?: string;

    /**
     * Reason for failure.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "reason" })
    reason?: string;

    /**
     * Remarks on the settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remarks" })
    remarks?: string;

    /**
     * Service charge applicable on settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "service_charge" })
    serviceCharge?: number;

    /**
     * Service tax applicable on settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "service_tax" })
    serviceTax?: number;

    /**
     * Settlement tax applicable on settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "settlement_charge" })
    settlementCharge?: number;

    /**
     * Date and time when the settlement was processed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "settlement_date" })
    settlementDate?: string;

    /**
     * Settlement initiation time.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "settlement_initiated_on" })
    settlementInitiatedOn?: string;

    /**
     * Settlement charge applicable on settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "settlement_tax" })
    settlementTax?: number;

    /**
     * Settlement type.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "settlement_type" })
    settlementType?: string;

    /**
     * Unique transaction reference number of the payment.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "settlement_utr" })
    settlementUtr?: string;

    /**
     * Status of the settlement.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

/**
 * OK
 */
export class FetchSettlement extends SpeakeasyBase {
    /**
     * Specify a value from where you want to fetch the settlement details in the API call.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cursor" })
    cursor?: string;

    @SpeakeasyMetadata({ elemType: FetchSettlementData })
    @Expose({ name: "data" })
    @Type(() => FetchSettlementData)
    data?: FetchSettlementData[];

    /**
     * Specify the number of settlements you want to fetch in the API call.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "limit" })
    limit?: number;
}
