/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { SavedInstrumentMeta } from "./savedinstrumentmeta";
import { Expose, Type } from "class-transformer";

/**
 * Status of the saved instrument.
 */
export enum InstrumentStatus {
    Active = "ACTIVE",
    Inactive = "INACTIVE",
}

/**
 * Type of the saved instrument
 */
export enum InstrumentType {
    Card = "card",
}

export class FetchAllSavedInstruments extends SpeakeasyBase {
    /**
     * cf_payment_id of the successful transaction done while saving instrument
     */
    @SpeakeasyMetadata()
    @Expose({ name: "afa_reference" })
    afaReference?: number;

    /**
     * Timestamp at which instrument was saved.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * customer_id for which the instrument was saved
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_id" })
    customerId?: string;

    /**
     * masked card number displayed to the customer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instrument_display" })
    instrumentDisplay?: string;

    /**
     * saved instrument id
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instrument_id" })
    instrumentId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "instrument_meta" })
    @Type(() => SavedInstrumentMeta)
    instrumentMeta?: SavedInstrumentMeta;

    /**
     * Status of the saved instrument.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instrument_status" })
    instrumentStatus?: InstrumentStatus;

    /**
     * Type of the saved instrument
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instrument_type" })
    instrumentType?: InstrumentType;

    /**
     * Unique id for the saved instrument
     */
    @SpeakeasyMetadata()
    @Expose({ name: "instrument_uid" })
    instrumentUid?: string;
}
