/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class LinkMetaEntity extends SpeakeasyBase {
    /**
     * Notification URL for server-server communication. It should be an https URL.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "notify_url" })
    notifyUrl?: string;

    /**
     * Allowed payment modes for this link. Pass comma-separated values among following options - "cc", "dc", "ccc", "ppc", "nb", "upi", "paypal", "app". Leave it blank to show all available payment methods
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_methods" })
    paymentMethods?: string;

    /**
     * The URL to which user will be redirected to after the payment is done on the link. Maximum length: 250.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "return_url" })
    returnUrl?: string;

    /**
     * If "true", link will directly open UPI Intent flow on mobile, and normal link flow elsewhere
     */
    @SpeakeasyMetadata()
    @Expose({ name: "upi_intent" })
    upiIntent?: boolean;
}
