/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LinkCustomerDetailsEntity } from "./linkcustomerdetailsentity";
import { LinkMetaEntity } from "./linkmetaentity";
import { LinkNotifyEntity } from "./linknotifyentity";
import { Expose, Type } from "class-transformer";

export class LinkCancelledResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cf_link_id" })
    cfLinkId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "customer_details" })
    @Type(() => LinkCustomerDetailsEntity)
    customerDetails?: LinkCustomerDetailsEntity;

    @SpeakeasyMetadata()
    @Expose({ name: "link_amount" })
    linkAmount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "link_amount_paid" })
    linkAmountPaid?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "link_auto_reminders" })
    linkAutoReminders?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "link_created_at" })
    linkCreatedAt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "link_currency" })
    linkCurrency?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "link_expiry_time" })
    linkExpiryTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "link_id" })
    linkId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "link_meta" })
    @Type(() => LinkMetaEntity)
    linkMeta?: LinkMetaEntity;

    @SpeakeasyMetadata()
    @Expose({ name: "link_minimum_partial_amount" })
    linkMinimumPartialAmount?: number;

    /**
     * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
     */
    @SpeakeasyMetadata()
    @Expose({ name: "link_notes" })
    linkNotes?: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "link_notify" })
    @Type(() => LinkNotifyEntity)
    linkNotify?: LinkNotifyEntity;

    @SpeakeasyMetadata()
    @Expose({ name: "link_partial_payments" })
    linkPartialPayments?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "link_purpose" })
    linkPurpose?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "link_status" })
    linkStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "link_url" })
    linkUrl?: string;
}
