/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LinkCustomerDetailsEntity } from "./linkcustomerdetailsentity";
import { PaymentURLObject } from "./paymenturlobject";
import { RefundURLObject } from "./refundurlobject";
import { SettlementURLObject } from "./settlementurlobject";
import { Expose, Type } from "class-transformer";

export class LinkOrdersResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cf_order_id" })
    cfOrderId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "customer_details" })
    @Type(() => LinkCustomerDetailsEntity)
    customerDetails?: LinkCustomerDetailsEntity;

    @SpeakeasyMetadata()
    @Expose({ name: "entity" })
    entity?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_amount" })
    orderAmount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "order_currency" })
    orderCurrency?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_expiry_time" })
    orderExpiryTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_note" })
    orderNote?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_status" })
    orderStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_token" })
    orderToken?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "payments" })
    @Type(() => PaymentURLObject)
    payments?: PaymentURLObject;

    @SpeakeasyMetadata()
    @Expose({ name: "refunds" })
    @Type(() => RefundURLObject)
    refunds?: RefundURLObject;

    @SpeakeasyMetadata()
    @Expose({ name: "settlements" })
    @Type(() => SettlementURLObject)
    settlements?: SettlementURLObject;
}
