/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class LinkCustomerDetailsEntity extends SpeakeasyBase {
    /**
     * Customer email address
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_email" })
    customerEmail?: string;

    /**
     * Customer name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_name" })
    customerName?: string;

    /**
     * Customer phone number
     */
    @SpeakeasyMetadata()
    @Expose({ name: "customer_phone" })
    customerPhone: string;
}
