/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class NBOffer extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bank_name" })
    bankName: string;
}
