/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Netbanking } from "./netbanking";
import { Expose, Type } from "class-transformer";

export class NetBankingPaymentMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "netbanking" })
    @Type(() => Netbanking)
    netbanking: Netbanking;
}
