/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NBOffer } from "./nboffer";
import { Expose, Type } from "class-transformer";

export class OfferNB extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "netbanking" })
    @Type(() => NBOffer)
    netbanking?: NBOffer;
}
