/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { All } from "./all";
import { Expose, Type } from "class-transformer";

export class OfferAll extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "all" })
    @Type(() => All)
    all: All;
}
