/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OfferType } from "./offertype";
import { Expose } from "class-transformer";

export class OfferFilters extends SpeakeasyBase {
    /**
     * Array of offer_type to be filtered.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "offer_type" })
    offerType?: OfferType[];
}
