/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class OfferMeta extends SpeakeasyBase {
    /**
     * Unique identifier for the Offer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "offer_code" })
    offerCode: string;

    /**
     * Description for the Offer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "offer_description" })
    offerDescription: string;

    /**
     * Expiry Time for the Offer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "offer_end_time" })
    offerEndTime: string;

    /**
     * Start Time for the Offer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "offer_start_time" })
    offerStartTime: string;

    /**
     * Title for the Offer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "offer_title" })
    offerTitle: string;
}
