/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EMIOffer } from "./emioffer";
import { Expose, Type } from "class-transformer";

export class OfferEMI extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "emi" })
    @Type(() => EMIOffer)
    emi: EMIOffer;
}
