/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

export enum OfferType {
    Discount = "DISCOUNT",
    Cashback = "CASHBACK",
    DiscountAndCashback = "DISCOUNT_AND_CASHBACK",
    NoCostEmi = "NO_COST_EMI",
}
