/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CardOffer } from "./cardoffer";
import { Expose, Type } from "class-transformer";

export class OfferCard extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => CardOffer)
    card: CardOffer;
}
