/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class OfferQueries extends SpeakeasyBase {
    /**
     * Amount of the order. OrderId of the order. Either of `order_id` or `order_amount` is mandatory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    /**
     * OrderId of the order. Either of `order_id` or `order_amount` is mandatory.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId?: string;
}
