/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WalletOffer } from "./walletoffer";
import { Expose, Type } from "class-transformer";

export class OfferWallet extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app" })
    @Type(() => WalletOffer)
    app?: WalletOffer;
}
