/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CashbackDetails } from "./cashbackdetails";
import { DiscountDetails } from "./discountdetails";
import { Expose, Type } from "class-transformer";

/**
 * Offer Type for the Offer.
 */
export enum OfferDetailsOfferType {
    Discount = "DISCOUNT",
    Cashback = "CASHBACK",
    DiscountAndCashback = "DISCOUNT_AND_CASHBACK",
    NoCostEmi = "NO_COST_EMI",
}

export class OfferDetails extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cashback_details" })
    @Type(() => CashbackDetails)
    cashbackDetails?: CashbackDetails;

    @SpeakeasyMetadata()
    @Expose({ name: "discount_details" })
    @Type(() => DiscountDetails)
    discountDetails?: DiscountDetails;

    /**
     * Offer Type for the Offer.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "offer_type" })
    offerType: OfferDetailsOfferType;
}
