/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OrderPayData } from "./orderpaydata";
import { Expose, Type } from "class-transformer";

/**
 * One of ["link", "custom", "form"]
 */
export enum OrderPayResponseAction {
    Link = "link",
    Custom = "custom",
    Form = "form",
}

/**
 * One of ["link", "collect", "qrcode"]. In an older version we used to support different channels like 'gpay', 'phonepe' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as 'link' and provider as 'gpay'
 */
export enum OrderPayResponseChannel {
    Link = "link",
    Collect = "collect",
    Qrcode = "qrcode",
}

/**
 * One of ["upi", "netbanking", "card", "app", "cardless_emi", "paylater"]
 */
export enum OrderPayResponsePaymentMethod {
    Netbanking = "netbanking",
    Card = "card",
    Upi = "upi",
    App = "app",
    CardlessEmi = "cardless_emi",
    Paylater = "paylater",
}

export class OrderPayResponse extends SpeakeasyBase {
    /**
     * One of ["link", "custom", "form"]
     */
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: OrderPayResponseAction;

    /**
     * Payment identifier created by Cashfree
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cf_payment_id" })
    cfPaymentId?: number;

    /**
     * One of ["link", "collect", "qrcode"]. In an older version we used to support different channels like 'gpay', 'phonepe' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as 'link' and provider as 'gpay'
     */
    @SpeakeasyMetadata()
    @Expose({ name: "channel" })
    channel?: OrderPayResponseChannel;

    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => OrderPayData)
    data?: OrderPayData;

    /**
     * One of ["upi", "netbanking", "card", "app", "cardless_emi", "paylater"]
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_method" })
    paymentMethod?: OrderPayResponsePaymentMethod;
}
