/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
 */
export enum OTPRequestAction {
    SubmitOtp = "SUBMIT_OTP",
    ResendOtp = "RESEND_OTP",
}

export class OTPRequest extends SpeakeasyBase {
    /**
     * The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
     */
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action: OTPRequestAction;

    /**
     * OTP to be submitted
     */
    @SpeakeasyMetadata()
    @Expose({ name: "otp" })
    otp: string;
}
