/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * The action that was invoked for this request.
 */
export enum OTPResponseEntityAction {
    SubmitOtp = "SUBMIT_OTP",
    ResendOtp = "RESEND_OTP",
}

/**
 * Status of the is action. Will be either failed or successful. If the action is successful, you should still call the authorization status to verify the final payment status.
 */
export enum AuthenticateStatus {
    Failed = "FAILED",
    Success = "SUCCESS",
}

/**
 * This is the response shared when merchant inovkes the OTP submit or resend API
 */
export class OTPResponseEntity extends SpeakeasyBase {
    /**
     * The action that was invoked for this request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: OTPResponseEntityAction;

    /**
     * Status of the is action. Will be either failed or successful. If the action is successful, you should still call the authorization status to verify the final payment status.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "authenticate_status" })
    authenticateStatus?: AuthenticateStatus;

    /**
     * The payment id for which this request was sent
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cf_payment_id" })
    cfPaymentId?: number;

    /**
     * Human readable message which describes the status in more detail
     */
    @SpeakeasyMetadata()
    @Expose({ name: "payment_message" })
    paymentMessage?: string;
}
