/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Paylater } from "./paylater";
import { Expose, Type } from "class-transformer";

export class PaylaterPaymentMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "paylater" })
    @Type(() => Paylater)
    paylater: Paylater;
}
