/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * One of ["kotak", "flexipay", "zestmoney", "lazypay", "olapostpaid","simpl", "freechargepaylater"]. Please note that Flexipay is offered by HDFC bank
 */
export enum PaylaterProvider {
    Kotak = "kotak",
    Flexipay = "flexipay",
    Zestmoney = "zestmoney",
    Lazypay = "lazypay",
    Olapostpaid = "olapostpaid",
    Simpl = "simpl",
    Freechargepaylater = "freechargepaylater",
}

export class Paylater extends SpeakeasyBase {
    /**
     * The channel for cardless EMI is always `link`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "channel" })
    channel?: string;

    /**
     * Customers phone number for this payment instrument. If the customer is not eligible you will receive a 400 error with type as 'invalid_request_error' and code as 'invalid_request_error'
     */
    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone?: string;

    /**
     * One of ["kotak", "flexipay", "zestmoney", "lazypay", "olapostpaid","simpl", "freechargepaylater"]. Please note that Flexipay is offered by HDFC bank
     */
    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider?: PaylaterProvider;
}
