/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WHdata } from "./whdata";
import { Expose, Type } from "class-transformer";

export class PaymentSuccessWebhook extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => WHdata)
    data?: WHdata;

    @SpeakeasyMetadata()
    @Expose({ name: "event_time" })
    eventTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: string;
}
