/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class PaymentMethodNetBankingInPaymentsEntity extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "channel" })
    channel: string;

    @SpeakeasyMetadata()
    @Expose({ name: "netbanking_bank_code" })
    netbankingBankCode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "netbanking_bank_name" })
    netbankingBankName: string;
}
