/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RefundSpeed } from "./refundspeed";
import { VendorSplit } from "./vendorsplit";
import { Expose, Type } from "class-transformer";

/**
 * Type of object
 */
export enum RefundsEntityEntity {
    Refund = "refund",
}

/**
 * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
 */
export class RefundsEntityMetadata extends SpeakeasyBase {}

/**
 * Method or speed of processing refund
 */
export enum RefundsEntityRefundMode {
    Standard = "STANDARD",
    Instant = "INSTANT",
}

/**
 * This can be one of ["SUCCESS", "PENDING", "CANCELLED", "ONHOLD", "FAILED"]
 */
export enum RefundsEntityRefundStatus {
    Success = "SUCCESS",
    Pending = "PENDING",
    Cancelled = "CANCELLED",
    Onhold = "ONHOLD",
}

/**
 * This can be one of ["PAYMENT_AUTO_REFUND", "MERCHANT_INITIATED", "UNRECONCILED_AUTO_REFUND"]
 */
export enum RefundsEntityRefundType {
    PaymentAutoRefund = "PAYMENT_AUTO_REFUND",
    MerchantInitiated = "MERCHANT_INITIATED",
    UnreconciledAutoRefund = "UNRECONCILED_AUTO_REFUND",
}

/**
 * Refund created
 */
export class RefundsEntity extends SpeakeasyBase {
    /**
     * Cashfree Payments ID of the payment for which refund is initiated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cf_payment_id" })
    cfPaymentId?: number;

    /**
     * Cashfree Payments ID for a refund
     */
    @SpeakeasyMetadata()
    @Expose({ name: "cf_refund_id" })
    cfRefundId?: string;

    /**
     * Time of refund creation
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: string;

    /**
     * Type of object
     */
    @SpeakeasyMetadata()
    @Expose({ name: "entity" })
    entity?: RefundsEntityEntity;

    /**
     * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => RefundsEntityMetadata)
    metadata?: RefundsEntityMetadata;

    /**
     * Merchant’s order Id of the order for which refund is initiated
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId?: string;

    /**
     * Time when refund was processed successfully
     */
    @SpeakeasyMetadata()
    @Expose({ name: "processed_at" })
    processedAt?: string;

    /**
     * Amount that is refunded
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_amount" })
    refundAmount?: number;

    /**
     * The bank reference number for refund
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_arn" })
    refundArn?: string;

    /**
     * Charges in INR for processing refund
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_charge" })
    refundCharge?: number;

    /**
     * Currency of the refund amount
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_currency" })
    refundCurrency?: string;

    /**
     * Merchant’s refund ID of the refund
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_id" })
    refundId?: string;

    /**
     * Method or speed of processing refund
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_mode" })
    refundMode?: RefundsEntityRefundMode;

    /**
     * Note added by merchant for the refund
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_note" })
    refundNote?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "refund_speed" })
    @Type(() => RefundSpeed)
    refundSpeed?: RefundSpeed;

    @SpeakeasyMetadata({ elemType: VendorSplit })
    @Expose({ name: "refund_splits" })
    @Type(() => VendorSplit)
    refundSplits?: VendorSplit[];

    /**
     * This can be one of ["SUCCESS", "PENDING", "CANCELLED", "ONHOLD", "FAILED"]
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_status" })
    refundStatus?: RefundsEntityRefundStatus;

    /**
     * This can be one of ["PAYMENT_AUTO_REFUND", "MERCHANT_INITIATED", "UNRECONCILED_AUTO_REFUND"]
     */
    @SpeakeasyMetadata()
    @Expose({ name: "refund_type" })
    refundType?: RefundsEntityRefundType;

    /**
     * Description of refund status
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status_description" })
    statusDescription?: string;
}
