/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class CardTokenDetails extends SpeakeasyBase {}

export class SavedInstrumentMeta extends SpeakeasyBase {
    /**
     * Issuing bank name of saved card
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_bank_name" })
    cardBankName?: string;

    /**
     * Issuing country of saved card
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_country" })
    cardCountry?: string;

    /**
     * card scheme/network of the saved card
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_network" })
    cardNetwork?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "card_token_details" })
    @Type(() => CardTokenDetails)
    cardTokenDetails?: CardTokenDetails;

    /**
     * Type of saved card
     */
    @SpeakeasyMetadata()
    @Expose({ name: "card_type" })
    cardType?: string;
}
