/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class TerminalDetails extends SpeakeasyBase {
    /**
     * The internal id that you use to map the terminal in your internal system
     */
    @SpeakeasyMetadata()
    @Expose({ name: "terminal_id" })
    terminalId: string;

    /**
     * Phone no assigned to the terminal
     */
    @SpeakeasyMetadata()
    @Expose({ name: "terminal_phone_no" })
    terminalPhoneNo: string;

    /**
     * To identify the type of terminal product in use, in this case it is SPOS
     */
    @SpeakeasyMetadata()
    @Expose({ name: "terminal_type" })
    terminalType: string;
}
