/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Upi } from "./upi";
import { Expose, Type } from "class-transformer";

export class UPIPaymentMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "upi" })
    @Type(() => Upi)
    upi: Upi;
}
