/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class VendorSplit extends SpeakeasyBase {
    /**
     * Amount which will be associated with this vendor
     */
    @SpeakeasyMetadata()
    @Expose({ name: "amount" })
    amount?: number;

    /**
     * Percentage of order amount which shall get added to vendor account
     */
    @SpeakeasyMetadata()
    @Expose({ name: "percentage" })
    percentage?: number;

    /**
     * Vendor id created in Cashfree system
     */
    @SpeakeasyMetadata()
    @Expose({ name: "vendor_id" })
    vendorId?: string;
}
