/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class WHcustomerDetails extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "customer_email" })
    customerEmail?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "customer_id" })
    customerId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "customer_name" })
    customerName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "customer_phone" })
    customerPhone?: string;
}
