/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WHcustomerDetails } from "./whcustomerdetails";
import { WHorder } from "./whorder";
import { WHpayment } from "./whpayment";
import { Expose, Type } from "class-transformer";

export class WHdata extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "customer_details" })
    @Type(() => WHcustomerDetails)
    customerDetails?: WHcustomerDetails;

    @SpeakeasyMetadata()
    @Expose({ name: "order" })
    @Type(() => WHorder)
    order?: WHorder;

    @SpeakeasyMetadata()
    @Expose({ name: "payment" })
    @Type(() => WHpayment)
    payment?: WHpayment;
}
