/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class WHorder extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "order_amount" })
    orderAmount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "order_currency" })
    orderCurrency?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "order_tags" })
    orderTags?: string;
}
