/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WHcard } from "./whcard";
import { Expose, Type } from "class-transformer";

export class WHpaymentMethod extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "card" })
    @Type(() => WHcard)
    card?: WHcard;
}
